// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const APP_ENV = (process.env.APP_ENV || 'dev').toLowerCase();
const DATABASE_PROVIDER = (process.env.DATABASE_PROVIDER || 'postgresql').toLowerCase();

export default defineConfig({
  schema: `prisma/schema.${APP_ENV}.${DATABASE_PROVIDER}.prisma`,
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
